# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'SeriesManager' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SeriesManager

  pod 'AFNetworking', '~> 3.1'
  pod 'AppController', '~> 0.4'
  pod 'Locksmith', '~> 3.0'
  pod 'ObjectMapper’, '~> 2.2'

end
